### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by rzvxa** [Malien/luar#3]
Hello,

what is the state of this project? Are you going to keep developing it? I'm working on a [programming language](https://fuse-lang.github.io/docs/home/) that would transpile to Lua.
I'm choosing Lua as my virtual machine and would love to run the bytecode directly instead of transpiling to Lua, This can be useful when I want to release a standalone virtual machine so you can have Fuse directly without using Lua + a transpiler.
I was exploring the internet looking for a project that reimplements Lua in either Rust or Zig, your project is far enough into development that it would be wiser to help with it instead of rolling my own runtime.

It is much simpler to reimplement Lua in Zig since it has such good interoperability with C and C++ libraries and has a really nice way of using custom allocators. Rust on the other hand can be a little bit ugly to work with for such a low-level situation however it brings more safety to the table compared to whatever Zig would ever offer, What is your experience with it? Is it worth continued development or is it better to drop it in favor of rewriting it in Zig?

I would love to hear back from you!

Thanks.

**Comment by Malien** [comment]
Hey there,

I'm terribly sorry for such a late answer. 

This project is mostly a research endeavour as part of my masters thesis. It doesn't event implement the latest revisions of the lua language. I am skeptical as to its practical application. It inferior in most regards to any of the widely-used and battle-tested implementations, such as PUC-RIO Lua, Luajit, luerl (if you need one in BEAM VM), luaj/luna (if you need one in JVM). If I were to ship a production application, my choice would be to bind to the C API of `luajit` (or through `mlua` rust crate). There is also https://github.com/kyren/piccolo from a person I crossed paths with, might be worth taking a look at.

It wouldn't be hard to write a compiler front-end for the fuse lang to be used in luar. And typed nature of the language does seem to land itself nicely into the typed bytecode of the reggie (the register based vm in luar). If you were to compile to the bytecode in interrim, then there is no serializable bytecode format defined, nor a verification pipeline present. It shouldn't be hard to define/implement though. I'm always open to contributions though. If this project does seem of interest to you, maybe we'll make something worthwhile of it ¯\_(ツ)_/¯.

As to use of Zig. Yeah. It does have a bunch of niceties that would apply here. And I may have already dropped the ball on the whole memory-safery Rust provides (there is a generous amount of `unsafe`). I've mainly chose Rust because of crates.io ecosystem of packages I make heavy use of. Plus, I just already know and like using Rust ¯\_(ツ)_/¯.

**Comment by rzvxa** [comment]
Hi, 

> I'm terribly sorry for such a late answer.

No worries mate, Don't even mention it.

> I am skeptical as to its practical application. It inferior in most regards to any of the widely-used and battle-tested implementations, such as PUC-RIO Lua, Luajit, luerl (if you need one in BEAM VM), luaj/luna (if you need one in JVM). 

Yeah, I can understand that. This experimental language I'm working on will have a customizable compiler with a thing called `features` which isn't documented yet. These are some special packages that contain compiler modules, For example, if you want to add a new keyword to the language for your domain-specific problem, Let's say you want to add support for inline SQL, You first create a new lexer rule, and parser logic to create the AST nodes, Then you can add linting rules, code generation, AST transformation or anything else which compiler have infrastructure to support. Any module(file) containing a feature would enforce its parent to import that feature.

I'm planning to release all experimental features with this approach so I make sure the interface is fast enough(although I would probably support both Rust modules and Fuse modules for compiler features).

There would be some internal backends by default that would target different flavors of Lua such as Lua 5.1 to 5.4, Luau, Pallene, etc. That's the language.

As a side project, I would like to experiment with a Lua-compatible runtime that won't have any frontend instead it provides a singular bytecode spec that can run Lua code from Lua 5.1 to 5.4 + LuaJIT (if I manage to get jit compilation going), Such VM can provide a solid foundation for any DSL that needs a runtime(either jitted or interpreted). And would be similar to native compiler backends such as LLVM but for interpreted languages.

> As to use of Zig. Yeah. It does have a bunch of niceties that would apply here. And I may have already dropped the ball on the whole memory-safery Rust provides (there is a generous amount of unsafe). I've mainly chose Rust because of crates.io ecosystem of packages I make heavy use of. Plus, I just already know and like using Rust ¯_(ツ)_/¯.

That's why initially thought of using Zig since it would be almost impossible to achieve JIT compilation without unsafe code. Even the interpreter would need unsafe code if we don't want to sacrifice performance.

In the end, I would like to thank you for your suggestions and for answering this PR in the first place.
